feat: Update to useRouter from next/navigation
47ng/next-usequerystate pull request #328
Opened 2023-05-15 06:33 UTC by andreisocaciu

Implemented the same functionality as before, but using the new Next.js 13.4 hooks from `'next/navigation`.

It only works in the `app` directory now, so this means it should be released under v2.0 because of this breaking change.

Closes: #327

2023-05-15 07:01 UTC, franky47 commented
Would there be a way to import this implementation in parallel to the previous one, using different import paths?

Eg:
```ts
// Using pages router
import { useQueryState } from 'next-usequerystate' // kept for compatibility
import { useQueryState } from 'next-usequerystate/pages' // explicit "legacy" import

// Using app router
import { useQueryState } from 'next-usequerystate/app'
```

2023-05-15 18:22 UTC, franky47 commented
@andreisocaciu I tried updating the deps in https://github.com/47ng/next-usequerystate/commit/c46254a7, but somehow it didn't end up in this PR. Could you try replicating those changes and I'll approve the CI runs.

2023-05-17 19:03 UTC, franky47 requested changes

2023-05-17 19:03 UTC, franky47 commented on .github/workflows/cd.yml
>        - uses: actions/setup-node@56899e050abffc08c2b3b61f3ec6a79a9dc3223d
Sorry about that, I realised that the `actions/setup-node` must also be bumped to v3:

```yml
- uses: actions/setup-node@v3
  with:
    node-version: lts/*
```

2023-06-01 22:40 UTC, MaxLeiter commented
FWIW `next/navigation` works in both pages and app. The types are different depending on if a `pages` folder is present -- in `pages` the new hooks can return `null` when `router.isReady` would be false.

2023-06-07 01:32 UTC, simonexmachina commented
Hello, I'm keen to use this in my project. Wondering if this will be merged soon, or if there's another fork that I can use?

2023-08-25 09:55 UTC, luisanton-io commented
This would be very helpful, hopefully merged soon...?

2023-08-28 21:40 UTC, iloveitaly commented
Same here!

2023-08-30 14:15 UTC, franky47 approved these changes

2023-08-30 14:38 UTC, franky47 commented
I've merged these changes into `next` (somehow the PR got stuck in conflict limbo..), with some changes to make it possible to use both the app and pages router, using different imports:
```ts
import {} from 'next-usequerystate' // uses the pages router by default for compatibility
import {} from 'next-usequerystate/pages' // explicit opt-in to pages router
import {} from 'next-usequerystate/app' // explicit opt-in to app router
```

I published `1.8.0-beta.1` to test it on my website that uses the app router, feel free to test that version and report back!

2023-08-30 14:38 UTC, closed without merging

2023-08-31 00:38 UTC, tryanmac commented
Works like a dream for me thanks all contributors!