prevent empty string while setting an empty array as value
47ng/next-usequerystate pull request #330
Opened 2023-05-31 11:15 UTC by prasannamestha

Fixes this issue: https://github.com/47ng/next-usequerystate/issues/329

2023-05-31 11:40 UTC, franky47 requested changes
**nitpick**: This may have unintended consequences, like dropping zeros from arrays of numbers.

**suggestion**: Performing a test on the query value to check for an explicit empty string would fix the issue while maintaining existing "falsy but not nullish" operations.

2023-06-01 11:12 UTC, franky47 requested changes

2023-06-01 11:12 UTC, franky47 commented on src/defs.ts
> +            value => !value !== null && value !== undefined && value !== ''
**nitpick**: This won't do either, as arrays of multiple string items can include empty elements. The heart of the issue comes from calling `.split` on an empty query string (not individual elements, but the whole query), so this case needs to be taken care of even before the query string is splitted/mapped/filtered.

Also, watch out for that stray negation on the null test.

2023-06-01 16:14 UTC, prasannamestha commented on src/defs.ts
> +            value => !value !== null && value !== undefined && value !== ''
You are right.. Will try to take care of this

2023-06-02 05:38 UTC, prasannamestha commented on src/defs.ts
> +            value => !value !== null && value !== undefined && value !== ''
My apologies for the stray negation, seems like a cat walked on my keyboard 😺 

Regarding the heart of the issue - isn't it caused because .split operation returns an array with empty string (`''.split(',')`)?

2023-06-03 12:21 UTC, franky47 commented on src/defs.ts
> +            value => !value !== null && value !== undefined && value !== ''
Yes indeed. When the `query` argument of the `parse` function is an empty string, an empty array should be returned directly, in order not to hit the `.split` call. Otherwise, the split/map/filter logic can perform its task.

2023-06-05 05:20 UTC, prasannamestha commented on src/defs.ts
> +            value => !value !== null && value !== undefined && value !== ''
Gotcha 👍 Updated the code

2023-06-05 06:50 UTC, franky47 approved these changes
**praise**: LGTM, thanks!

2023-06-05 06:52 UTC, merged

2023-06-05 16:41 UTC, prasannamestha commented
@franky47 thanks for merging the PR. Could you please let me know when you plan to release this fix?